#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/under/ravencore/home \
			--quiet --gecos "under ravencore" ravencore
		chown -R ravencore /opt/under/ravencore/home
		ln -s /etc/nginx/sites-available/nginx-ravencore /etc/nginx/sites-enabled
		rm -f /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
		systemctl enable mongod.service
		service mongod start
		mkdir /etc/systemd/system/nginx.service.d
		printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" > /etc/systemd/system/nginx.service.d/override.conf
		systemctl daemon-reload
		systemctl restart nginx
		systemctl restart ravencore
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
