#! /bin/sh -e

case "$1" in
	install|upgrade)
		echo '# installed by ravencore package' > /etc/apt/sources.list.d/ravencore-nodesource.list
		apt-get install -qy python-minimal
		curl https://deb.nodesource.com/node_10.x/pool/main/n/nodejs/nodejs_10.5.0-1nodesource1_amd64.deb > node.deb
		dpkg -i node.deb
		rm node.deb
		echo 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse' >> /etc/apt/sources.list.d/nodesource.list
		apt-key adv --keyserver keyserver.ubuntu.com --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
		;;
	abort-upgrade)
	;;
	*)
	    echo "preinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac

exit 0
