#!/bin/bash -e

INSTALL_PATH="/opt/under/ravencore/"
BIN=$(realpath "$INSTALL_PATH"/ravencore/node_modules/ravencore-node/bin/raven-*/bin/)
DATA="$INSTALL_PATH/home/.ravencore/data"
CONF="$DATA/raven.conf"

exec sudo -u ravencore "$BIN/ravend" --conf="$CONF" --datadir="$DATA" "$@"
